name: Deploy Complex
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true cygnetops/react-test npm test
      
      - run: docker build -t emirfmutlu/multi-client ./client
      - run: docker build -t emirfmutlu/multi-nginx ./nginx
      - run: docker build -t emirfmutlu/multi-server ./server
      - run: docker build -t emirfmutlu/multi-worker ./worker
      
      
      - run: docker push emirfmutlu/multi-client
      - run: docker push emirfmutlu/multi-nginx
      - run: docker push emirfmutlu/multi-server
      - run: docker push emirfmutlu/multi-worker


 

